author: Firas Safa a.k.a. The Inked Engineer
author_url: http://theinkedengineer.com
copyright: 2019 TheInkedEngineer
readme: README.md
module: SwiftKnife
github_url: https://github.com/TheInkedEngineer/
github_file_prefix: https://github.com/TheInkedEngineer/blob/master
module_version: 1.0
xcodebuild_arguments: [clean,build,-scheme,Production]
output: docs/1.0

