name: SwiftKnife

options:
  minimumXcodeGenVersion: "2.5.0"
  bundleIdPrefix: com.theInkedEngineer
  indentWidth: 2
  xcodeVersion: 10.2.1
  deploymentTarget:
    iOS: "10.0"
  generateEmptyDirectories: true
  
targets:
  SwiftKnife:
    type: framework
    platform: iOS
    attributes:
      ProvisioningStyle: Automatic
    sources: [SwiftKnife]
    info:
      path: SwiftKnife/Resources/Info.plist
      properties:
        CFBundleIdentifier: "$(PRODUCT_BUNDLE_IDENTIFIER)"
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleExecutable: "$(EXECUTABLE_NAME)"
        CFBundleName: "$(PRODUCT_NAME)"
        CFBundleDevelopmentRegion: "$(DEVELOPMENT_LANGUAGE)"
        CFBundleShortVersionString: "3.5.0"
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundlePackageType: "FMWK"

  SwiftKnifeTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: SwiftKnifeTests
    dependencies:
      - target: SwiftKnife
    settings:
      INFOPLIST_FILE: SwiftKnifeTests/Resources/Info.plist

schemes:
  Developement:
      build:
        targets:
          SwiftKnife: all
          SwiftKnifeTests: [test]
      test:
        gatherCoverageData: true
        randomExecutionOrder: false
        targets: [SwiftKnifeTests]
      archive:
        customArchiveName: SwiftKnife_Development
        revealArchiveInOrganizer: false
